'use client';

import { SessionProvider } from 'next-auth/react';
import type { Metadata } from "next";
import { Suspense } from "react";
import { Navbar } from '../components/layout/navbar'
import { Inter } from 'next/font/google'
import { ConfigProvider } from 'antd';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Head from "next/head";
import { Layout } from "./customLayout";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   manifest:'/manifest.webmanifest'
// };

export default function RootLayout({ children, }: { children: React.ReactNode }) {

  return (
    <html lang="en" className={inter.className}>
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body style={{ margin: '0px' }} >
      <SessionProvider>
        <ConfigProvider theme={{ token: { fontFamily: "'__Inter_aaf875', __Inter_Fallback_aaf875" } }}>
          <AntdRegistry>
            <Layout>
              <Suspense>
                {/* <SessionProvider>{children}</SessionProvider> */}
                {children}
              </Suspense>
            </Layout>
          </AntdRegistry>
        </ConfigProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
